version: '3'
services:
  web:
    build:
      context: ./web-frontend # Dockerfile保存場所
      dockerfile: Dockerfile # Dockerfileファイル名
    image: gl-web # docker image name
    container_name: gl-web # docker container name
    ports:
      - 80:80

  app:
    build:
      context: ./docker/backend # Dockerfile保存場所
      dockerfile: Dockerfile # Dockerfileファイル名
    image: gl-app # イメージ名
    container_name: gl-app # コンテナ名
    ports: # ポート接続
      - 3000:3000
    volumes: # mount workdir
      - ./web-frontend:/hosting
      - /var/run/docker.sock:/var/run/docker.sock
    command: [sh, -c, npm install && npm run build && npm run express:run]
