version: "2"
services:
  crate-repository:
    build: ./docker/shell/create-repository
    image: create-repository

  git-commit:
    build: ./docker/shell/commit
    image: git-commit

  git-branch:
    build: ./docker/shell/branch
    image: git-branch

  git-amend:
    build: ./docker/shell/amend
    image: git-amend

  git-checkout:
    build: ./docker/shell/checkout
    image: git-checkout

  github-create-repository:
    build: ./docker/shell/github-create-repository
    image: github-create-repository

  web:
    build:
      context: ./
      dockerfile: docker/deploy/frontend/Dockerfile
    image: gl-web
    container_name: gl-web
    ports:
      - 80:80

  app:
    build:
      context: ./
      dockerfile: docker/deploy/backend/Dockerfile
    image: gl-app
    container_name: gl-app
    ports:
      - 3000:3000
    volumes:
      - ./web:/hosting
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      [
        sh,
        -c,
        "npm install && npm install sqlite3 && npm run build && npm run express:run",
      ]
