version: '2'
services:
  web:
    build:
      context: ./ # Dockerfile保存場所
      dockerfile: docker/deploy/frontend/Dockerfile # Dockerfileファイル名
    image: gl-web # docker image name
    container_name: gl-web # docker container name
    ports:
      - 80:80
    depends_on: 
      - app

  app:
    build:
      context: ./ # Dockerfile保存場所
      dockerfile: docker/deploy/backend/Dockerfile # Dockerfileファイル名
    image: gl-app # イメージ名
    container_name: gl-app # コンテナ名
    ports: # ポート接続
      - 3000:3000
    volumes: # mount workdir
      - ./web:/hosting
      - /var/run/docker.sock:/var/run/docker.sock
    command: [
        sh,
        -c,
        'npm install && npm install sqlite3 && npm run build && npm run express:run',
      ]
