version: '3'
services:
  crate-repository:
    build: ./docker/shell/create-repository
    image: create-repository

  git-commit:
    build: ./docker/shell/commit
    image: git-commit

  git-branch:
    build: ./docker/shell/branch
    image: git-branch

  app:
    build:
      context: ./ # Dockerfile保存場所
      dockerfile: docker/backend/Dockerfile # Dockerfileファイル名
    image: gl-app # イメージ名
    container_name: gl-app # コンテナ名
    ports: # ポート接続
      - 3000:3000
    volumes: # mount workdir
      - ./web:/hosting
      - /var/run/docker.sock:/var/run/docker.sock
