version: '2'
services:
  crate-repository:
    build: ./docker/shell/create-repository
    image: create-repository

  git-commit:
    build: ./docker/shell/commit
    image: git-commit

  git-branch:
    build: ./docker/shell/branch
    image: git-branch

  git-amend:
    build: ./docker/shell/amend
    image: git-amend

  git-checkout:
    build: ./docker/shell/checkout
    image: git-checkout

  github-create-repository:
    build: ./docker/shell/github-create-repository
    image: github-create-repository

  # web:
  #   build:
  #     context: ./ # Dockerfile保存場所
  #     dockerfile: docker/deploy/frontend/Dockerfile # Dockerfileファイル名
  #   image: gl-web # docker image name
  #   container_name: gl-web # docker container name
  #   ports:
  #     - 80:80

  app:
    build:
      context: ./ # Dockerfile保存場所
      dockerfile: docker/deploy/backend/Dockerfile # Dockerfileファイル名
    image: gl-app # イメージ名
    container_name: gl-app # コンテナ名
    ports: # ポート接続
      - 80:3000
    volumes: # mount workdir
      - ./web:/hosting
      - /var/run/docker.sock:/var/run/docker.sock
    command: [
        sh,
        -c,
        'npm install && npm install sqlite3 && npm run build && npm run express:run',
      ]
